# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ScmKRohCjfbKXVju9XhsfOOdbl4y7AZ
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import numpy as np

app = Flask(__name__)
CORS(app)

model = joblib.load('vino_veritas_model.pkl')
scaler = joblib.load('scaler.pkl')

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.get_json()
        input_list = [
            data['fixed acidity'], data['volatile acidity'], data['citric acid'],
            data['residual sugar'], data['chlorides'], data['free sulfur dioxide'],
            data['total sulfur dioxide'], data['density'], data['pH'],
            data['sulphates'], data['alcohol']
        ]

        columns = np.array(input_list).reshape(1, 11)
        columns_scaled = scaler.transform(columns)
        prediction = model.predict(columns_scaled)
        if prediction[0] == 1:
            result = "Good"
        else:
            result = "Bad"

        return jsonify({'prediction': result})

    except Exception as e:
        return jsonify({"error": str(e)}), 400

if __name__ == '__main__':
    app.run(debug=True)
